import type { PortfolioContent } from "../types/content";

export const cs: PortfolioContent = {
  nav: {
    brand: "DK",
    role: "Značka & růst",
    items: [
      { label: "Intro", href: "#top" },
      { label: "Projekty", href: "#case-studies" },
      { label: "Výstupy", href: "#evidence" },
      { label: "Jak pracuji", href: "#how-i-work" },
      { label: "Skills", href: "#skills" },
      { label: "Kontakt", href: "#contact" },
    ],
    languageLabel: "Jazyk",
    downloadCv: "Stáhnout CV",
    backToTopLabel: "Zpět nahoru",
    toggleMenuLabel: "Otevřít nebo zavřít menu",
  },
  hero: {
    eyebrow: "Manažer značky a růstu · Praha",
    headline: "Měním business příležitosti v",
    highlightedWord: "růstové projekty.",
    subheadline:
      "Propojuji produktový marketing, značku, výkon, data a týmy tak, aby se nové služby nejen dostaly na trh, ale našly si místo u zákazníků.",
    name: "David Koller",
    role: "Manažer značky a růstu",
    domains: "E-commerce · Fintech · Služby pro podnikatele",
    trajectory: "",
    primaryCta: "Prohlédnout projekty",
    secondaryCta: "Stáhnout CV",
    systemLabel: "Marketingový systém / co propojuji",
    systemCenter: "Přínos pro business",
    systemNodes: ["Značka", "Produkt", "Výkon", "Zákazník", "Obchod", "Týmy"],
    scrollLabel: "Vybrat cestu portfoliem",
  },
  guidedPath: {
    eyebrow: "Začněte tady",
    prompt: "Máte málo času? Začněte tady.",
    title: "Vyberte, čím chcete začít.",
    items: [
      {
        number: "01",
        title: "Projekty",
        body: "Podívat se na problémy, které jsem pomáhal řešit.",
        href: "#case-studies",
      },
      {
        number: "02",
        title: "Výstupy",
        body: "Vidět videa, kampaně a veřejné výstupy.",
        href: "#evidence",
      },
      {
        number: "03",
        title: "Jak pracuji",
        body: "Pochopit můj způsob práce.",
        href: "#how-i-work",
      },
      {
        number: "04",
        title: "CV / Kontakt",
        body: "Přejít rovnou k dalšímu kroku.",
        href: "#contact",
      },
    ],
  },
  businessImpact: {
    eyebrow: "01 / Business dopad",
    title: "Dopad v číslech.",
    intro:
      "Vybrané důkazy z projektů, které jsem pomáhal pozicovat, komunikovat a dostat k zákazníkům.",
    metrics: [
      {
        value: "12 000+",
        label: "klientů",
        project: "SHOPTET PAY",
        role: "Lifecycle a retenční komunikace v období růstu z 10k+ klientů.",
        proofType: "MĚŘÍTKO",
      },
      {
        value: "#1",
        label: "nejpoužívanější brána na Shoptetu od roku 2025",
        project: "SHOPTET PAY",
        role: "Hodnotová argumentace v cenově citlivé kategorii plateb.",
        proofType: "POZICE NA TRHU",
      },
      {
        value: "5 000+",
        label: "e-shopů",
        project: "SHOPTET BALÍKY",
        role: "GTM komunikace napříč dopravci a trhy.",
        proofType: "MĚŘÍTKO",
      },
      {
        value: "1 000+",
        label: "uživatelů / pokladen",
        project: "SHOPTET POKLADNA",
        role: "Launch, migrační komunikace a práce se zpětnou vazbou.",
        proofType: "DORUČENÍ",
      },
      {
        value: "10+",
        label: "produktových / GTM launchů",
        project: "NAPŘÍČ SLUŽBAMI",
        role: "Launch workstreamy napříč platbami, logistikou, pokladnou a financováním.",
        proofType: "DORUČENÍ",
      },
    ],
  },
  profile: {
    eyebrow: "01 / Profil",
    title: "Nejsem specialista na jeden marketingový kanál.",
    intro:
      "Moje zkušenost sahá od produktového marketingu přes výkon až ke značce. Díky tomu se nedívám jen optikou jednoho kanálu a pro každý problém hledám správnou páku.",
    cards: [
      {
        number: "01",
        title: "Značka jako obchodní aktivum",
        descriptor: "Převádím vizi do směru, se kterým dokážou pracovat kreativní týmy.",
        body: "Značkou vytvářím jasný směr, důvěru a odlišení, které podporují obchodní výsledky, ne jen povědomí.",
        featured: true,
      },
      {
        number: "02",
        title: "Růst za hranicí akvizice",
        descriptor: "Propojuji získání zákazníka, adopci a udržení.",
        body: "Přemýšlím nad celou cestou od akvizice přes první použití až po dlouhodobou hodnotu, kterou zákazník skutečně vnímá.",
      },
      {
        number: "03",
        title: "Výkon podložený daty",
        descriptor: "Držím marketing odpovědný vůči číslům.",
        body: "Vycházím z práce s KPI, analytikou, konverzními cestami a vyhodnocováním návratnosti marketingových investic.",
      },
      {
        number: "04",
        title: "Propojení specialistů a týmů",
        descriptor: "Spojuji lidi kolem společného směru pro trh.",
        body: "Dokážu stát mezi produktem, obchodem, péčí o zákazníky, daty, designem, specialisty, agenturami a partnery a přeložit jejich potřeby do společného postupu.",
      },
    ],
  },
  foundations: {
    eyebrow: "02 / Co mě formovalo",
    title: "Od kampaní ke strategické odpovědnosti.",
    intro:
      "Začínal jsem ve výkonu, kde jsem se naučil číst data, hlídat návratnost a nést odpovědnost za výsledek. Product marketing, positioning a růst služeb přidaly kontext, odlišení a práci napříč týmy. Z těchto základů vznikl můj Marketing OS.",
    layers: [
      {
        title: "Výkonová disciplína",
        body: "Kampaně, KPI, analytika, konverzní cesty a návratnost.",
        label: "MĚŘIT",
      },
      {
        title: "Business a fintech kontext",
        body: "Bankovnictví, platby, e-commerce a služby pro podnikatele.",
        label: "POCHOPIT",
      },
      {
        title: "Značka a kreativní směr",
        body: "Positioning, messaging a kreativní směr, které dávají službě jasné místo na trhu.",
        label: "ODLIŠIT",
      },
      {
        title: "Propojování týmů",
        body: "Slaďuji produkt, obchod, péči, data, kreativní výstupy a externí partnery kolem jednoho směru.",
        label: "PROPOJIT",
      },
    ],
    centerLabel: "Marketing OS",
    centerSubline: "STRATEGIE × EXEKUCE × VEDENÍ",
  },
  operatingSystem: {
    eyebrow: "03 / Jak pracuji",
    title: "Jak dostávám strategii na trh.",
    intro:
      "Jednoduchý pracovní rytmus od nejasné priority ke spuštěné a průběžně zlepšované iniciativě.",
    steps: [
      {
        number: "01",
        title: "Pochopit",
        body: "Vyjasnit problém, bariéru zákazníka a omezení.",
      },
      {
        number: "02",
        title: "Zarámovat",
        body: "Pojmenovat positioning, publikum a hlavní argument.",
      },
      {
        number: "03",
        title: "Propojit týmy",
        body: "Sladit vlastníky, kanály a výstupy v jednom plánu.",
      },
      {
        number: "04",
        title: "Spustit",
        body: "Doručit komunikaci pro trh a podporu obchodu.",
      },
      {
        number: "05",
        title: "Měřit",
        body: "Sledovat adopci, konverze, zpětnou vazbu a obchodní signály.",
      },
      {
        number: "06",
        title: "Zlepšovat",
        body: "Podle důkazů upravovat argumenty, kanály a další směr.",
      },
    ],
    loopLabel: "A pak zpět k problému — s lepšími informacemi.",
  },
  casesIntro: {
    eyebrow: "02 / Projekty",
    title: "Business příběhy, ne galerie kampaní.",
    intro: "Vybrané projekty podle problému, který bylo potřeba řešit.",
    detailLabel: "Otevřít projekt",
    selectedLabel: "Vybraný projekt",
    viewDetailLabel: "Zobrazit detail",
    viewedLabel: "Zobrazeno",
    detailRegionLabel: "detail projektu",
    problemSolvedLabel: "Vyřešený problém",
    myRoleLabel: "Moje role",
    proofImpactLabel: "Důkaz / dopad",
    contextLabel: "Kontext",
    challengeLabel: "Business výzva",
    strategicBetLabel: "Strategická sázka",
    strategicLinesLabel: "Komunikační směry",
    orchestrationLabel: "Co jsem propojil a řídil",
    impactLabel: "Směr dopadu",
    proofLabel: "Důkazy a výstupy",
    proofIntro:
      "Veřejné důkazy a bezpečné popisy interní práce bez citlivých údajů.",
    showMoreLabel: "Zobrazit více detailů",
    showLessLabel: "Zobrazit méně",
    deliveredLabel: "Co jsem doručil",
    nextLabel: "Dál: výstupy",
  },
  floatingNav: {
    label: "Sekce portfolia",
    items: [
      { label: "Intro", href: "#top" },
      { label: "Dopad", href: "#impact" },
      { label: "Projekty", href: "#case-studies" },
      { label: "Výstupy", href: "#evidence" },
      { label: "Jak pracuji", href: "#how-i-work" },
      { label: "Skills", href: "#skills" },
      { label: "Kontakt", href: "#contact" },
    ],
  },
  howIWork: {
    eyebrow: "04 / Jak pracuji",
    title: "Jak dostávám strategii na trh.",
    intro:
      "Čtyři základy formují můj přístup. Šest kroků dostává práci od problému na trh.",
    foundationsLabel: "Základy",
    deliveryLabel: "Pracovní cyklus",
    nextLabel: "Dál: Skills",
  },
  leadership: {
    eyebrow: "05 / Skills",
    title: "Schopnosti, které se navzájem násobí.",
    intro:
      "Stručný přehled schopností, které používám nejčastěji.",
    acceleratorLabel: "",
  },
  evidencePlaceholder: {
    label: "03 / Galerie výstupů",
    title: "Výstupy, které došly na trh.",
    body:
      "Veřejné výstupy z kampaní, video produkce, zákaznických příběhů a launch komunikace.",
    openVideoLabel: "Přehrát na YouTube",
    openProofLabel: "Otevřít veřejný výstup",
    videoThumbnailLabel: "náhled videa",
    featuredLabel: "Hlavní výstup",
    previousPhotoLabel: "Předchozí produkční fotografie",
    nextPhotoLabel: "Další produkční fotografie",
    nextLabel: "Dál: jak pracuji",
  },
  closing: {
    eyebrow: "06 / Další kapitola",
    title: "Nejen marketingová exekuce. Odpovědnost za dopad.",
    body: "Nenajímáte si mě na izolované marketingové úkoly. Získáváte člověka, který dokáže propojit positioning, kanály, týmy, zákaznický insight a výkon tak, aby marketing podporoval konkrétní business cíle.",
    statement:
      "Další krok pro mě znamená roli, kde se potkává značka, růst, business odpovědnost a práce s týmy.",
    primaryCta: "Pojďme se spojit",
    secondaryCta: "Stáhnout CV",
    linkedinCta: "LinkedIn",
  },
  footer: {
    location: "Praha, Česko",
    email: "E-mail",
    linkedin: "LinkedIn",
    cv: "Stáhnout CV",
    note: "Interaktivní portfolio marketingového vedení.",
  },
};
