import type { PortfolioContent } from "../types/content";

export const en: PortfolioContent = {
  nav: {
    brand: "DK",
    role: "Brand & Growth",
    items: [
      { label: "Intro", href: "#top" },
      { label: "Projects", href: "#case-studies" },
      { label: "Proof", href: "#evidence" },
      { label: "How I work", href: "#how-i-work" },
      { label: "Skills", href: "#skills" },
      { label: "Contact", href: "#contact" },
    ],
    languageLabel: "Language",
    downloadCv: "Download CV",
    backToTopLabel: "Back to top",
    toggleMenuLabel: "Toggle menu",
  },
  hero: {
    eyebrow: "Brand & Growth Manager · Prague",
    headline: "I turn business opportunities into",
    highlightedWord: "growth projects.",
    subheadline:
      "I connect product marketing, brand, performance, data and teams to turn business priorities into market impact.",
    name: "David Koller",
    role: "Brand & Growth Manager",
    domains: "E-commerce · Fintech · SME Services",
    trajectory: "",
    primaryCta: "View projects",
    secondaryCta: "Download CV",
    systemLabel: "Marketing system / what I connect",
    systemCenter: "Business impact",
    systemNodes: [
      "Brand",
      "Product",
      "Performance",
      "Customer",
      "Sales",
      "Teams",
    ],
    scrollLabel: "Choose a path through the portfolio",
  },
  guidedPath: {
    eyebrow: "Start here",
    prompt: "Short on time? Start here.",
    title: "Choose what you want to see first.",
    items: [
      {
        number: "01",
        title: "Projects",
        body: "See the business problems I helped solve.",
        href: "#case-studies",
      },
      {
        number: "02",
        title: "Proof",
        body: "View videos, campaigns and public outputs.",
        href: "#evidence",
      },
      {
        number: "03",
        title: "How I work",
        body: "Understand my operating model.",
        href: "#how-i-work",
      },
      {
        number: "04",
        title: "CV / Contact",
        body: "Skip to the practical next step.",
        href: "#contact",
      },
    ],
  },
  businessImpact: {
    eyebrow: "01 / Business impact",
    title: "Business impact at a glance.",
    intro:
      "Selected proof around projects I helped position, market and bring to customers.",
    metrics: [
      {
        value: "10k+ → 12k+",
        label: "clients",
        project: "SHOPTET PAY",
        role: "Lifecycle and retention communication during service growth.",
        proofType: "SCALE",
      },
      {
        value: "#1 since 2025",
        label: "most used gateway on Shoptet",
        project: "SHOPTET PAY",
        role: "Value narrative in a price-sensitive category.",
        proofType: "MARKET POSITION",
      },
      {
        value: "5,000+",
        label: "e-shops",
        project: "SHOPTET BALÍKY",
        role: "GTM communication across carriers and markets.",
        proofType: "SCALE",
      },
      {
        value: "1,000+",
        label: "users / cash registers",
        project: "SHOPTET POKLADNA",
        role: "Launch, migration communication and feedback loops.",
        proofType: "DELIVERY",
      },
      {
        value: "10+",
        label: "product / GTM launches",
        project: "CROSS-SERVICE DELIVERY",
        role: "Launch workstreams across payments, logistics, POS and financing.",
        proofType: "DELIVERY",
      },
    ],
  },
  profile: {
    eyebrow: "01 / Executive profile",
    title: "Built for marketing leadership, not a single-channel box.",
    intro:
      "My experience spans product marketing, performance and brand. That range lets me see beyond individual channels and choose the right lever for the problem.",
    cards: [
      {
        number: "01",
        title: "Brand as a commercial asset",
        descriptor: "Turning vision into creative direction teams can execute.",
        body: "I use brand to create clarity, trust and differentiation that supports business outcomes, not just awareness.",
        featured: true,
      },
      {
        number: "02",
        title: "Growth beyond acquisition",
        descriptor: "Connecting acquisition, adoption and retention.",
        body: "I think across acquisition, adoption, retention, lifecycle communication and the value customers actually experience.",
      },
      {
        number: "03",
        title: "Performance discipline underneath",
        descriptor: "Keeping marketing accountable to numbers.",
        body: "My foundation is built on KPI ownership, analytics, funnels and return on marketing investment.",
      },
      {
        number: "04",
        title: "Connecting specialists and teams",
        descriptor: "Aligning people around one direction for the market.",
        body: "I can stand between product, sales, customer care, data, design, specialists, agencies and partners and translate their needs into one shared direction.",
      },
    ],
  },
  foundations: {
    eyebrow: "02 / What built me",
    title: "Built from execution into strategic ownership.",
    intro:
      "I started in performance, learning to read data, protect return and stay accountable. Product marketing, positioning and service growth then added context, differentiation and cross-team ownership. Those foundations became my Marketing OS.",
    layers: [
      {
        title: "Performance discipline",
        body: "Campaigns, KPIs, analytics, conversion paths and return.",
        label: "MEASURE",
      },
      {
        title: "Business & fintech context",
        body: "Banking, payments, e-commerce and services for entrepreneurs.",
        label: "UNDERSTAND",
      },
      {
        title: "Brand & creative direction",
        body: "Positioning, messaging and creative direction that create a clear place in the market.",
        label: "DIFFERENTIATE",
      },
      {
        title: "Cross-team delivery",
        body: "Aligning product, commercial, customer care, data, creative work and external partners around one market direction.",
        label: "CONNECT",
      },
    ],
    centerLabel: "Marketing OS",
    centerSubline: "STRATEGY × EXECUTION × LEADERSHIP",
  },
  operatingSystem: {
    eyebrow: "03 / Operating system",
    title: "How I turn strategy into market impact.",
    intro:
      "A practical loop for moving from an ambiguous priority to a launched and improving initiative.",
    steps: [
      {
        number: "01",
        title: "Diagnose",
        body: "Clarify the problem, customer barrier and constraints.",
      },
      {
        number: "02",
        title: "Frame",
        body: "Define the positioning, audience and value argument.",
      },
      {
        number: "03",
        title: "Orchestrate",
        body: "Align owners, channels and assets around one plan.",
      },
      {
        number: "04",
        title: "Launch",
        body: "Deliver the market-facing communication and commercial support.",
      },
      {
        number: "05",
        title: "Measure",
        body: "Track adoption, conversion, feedback and commercial signals.",
      },
      {
        number: "06",
        title: "Iterate",
        body: "Use evidence to improve the message, channels and direction.",
      },
    ],
    loopLabel: "Then back to the problem—with better information.",
  },
  casesIntro: {
    eyebrow: "02 / Project explorer",
    title: "Business projects, not campaign galleries.",
    intro: "Choose the business problem you want to explore.",
    detailLabel: "Open project",
    selectedLabel: "Selected project",
    viewDetailLabel: "View detail",
    viewedLabel: "Viewed",
    detailRegionLabel: "project detail",
    problemSolvedLabel: "Problem solved",
    myRoleLabel: "My role",
    proofImpactLabel: "Proof / impact",
    contextLabel: "Context",
    challengeLabel: "Business challenge",
    strategicBetLabel: "Strategic bet",
    strategicLinesLabel: "Strategic lines",
    orchestrationLabel: "What I orchestrated",
    impactLabel: "Impact direction",
    proofLabel: "Proof & evidence",
    proofIntro:
      "Selected public evidence and concise descriptions of supporting work.",
    showMoreLabel: "Show more detail",
    showLessLabel: "Show less detail",
    deliveredLabel: "What I delivered",
    nextLabel: "Next: See proof",
  },
  floatingNav: {
    label: "Portfolio sections",
    items: [
      { label: "Intro", href: "#top" },
      { label: "Impact", href: "#impact" },
      { label: "Projects", href: "#case-studies" },
      { label: "Proof", href: "#evidence" },
      { label: "How", href: "#how-i-work" },
      { label: "Skills", href: "#skills" },
      { label: "Contact", href: "#contact" },
    ],
  },
  howIWork: {
    eyebrow: "04 / How I work",
    title: "How I bring strategy to market.",
    intro:
      "Four foundations shape the work. Six steps move it from problem to market.",
    foundationsLabel: "Foundations",
    deliveryLabel: "Delivery loop",
    nextLabel: "Next: View skills",
  },
  leadership: {
    eyebrow: "05 / Skills",
    title: "The leadership stack I bring.",
    intro:
      "A compact index of the capabilities I use most often.",
    acceleratorLabel: "",
  },
  evidencePlaceholder: {
    label: "03 / Proof gallery",
    title: "Proof in the market.",
    body:
      "Public outputs from campaigns, video production, customer stories and launch communication.",
    openVideoLabel: "Watch on YouTube",
    openProofLabel: "Open public proof",
    videoThumbnailLabel: "video thumbnail",
    featuredLabel: "Featured proof",
    previousPhotoLabel: "Previous production photo",
    nextPhotoLabel: "Next production photo",
    nextLabel: "Next: How I work",
  },
  closing: {
    eyebrow: "06 / The next chapter",
    title: "Not just marketing delivery. Marketing ownership.",
    body: "You do not hire me for isolated marketing tasks. You hire me to turn business opportunities into a marketing system that connects positioning, channels, teams, customer insight and measurable business impact.",
    statement:
      "The next step is a role where brand, growth, business ownership and team delivery meet.",
    primaryCta: "Let’s talk",
    secondaryCta: "Download CV",
    linkedinCta: "Open LinkedIn",
  },
  footer: {
    location: "Prague, Czechia",
    email: "Email",
    linkedin: "LinkedIn",
    cv: "Download CV",
    note: "Built as an interactive leadership portfolio.",
  },
};
